typedef void *MyThread;
void MyThreadInit(void(*start_funct)(void *), void *args);
MyThread MyThreadCreate(void(*start_funct)(void *), void *args);
void MyThreadYield(void);
void MyThreadExit(void);
int MyThreadJoin(MyThread thread);
void MyThreadJoinAll(void);
typedef void *MySemaphore;
MySemaphore MySemaphoreInit(int initialValue);
int MySemaphoreDestroy(MySemaphore sem);
void MySemaphoreWait(MySemaphore sem);
void MySemaphoreSignal(MySemaphore sem);